const skills = [
    "Ensures accountability",
    "Action oriented",
    "Manages ambiguity",
    "Attracts top talent",
    "Business insight",
    "Collaborates",
    "Communicates effectively",
    "Manages conflict",
    "Courage",
    "Customer Focus",
    "Decision quality",
    "Develops talent",
    "Values differences",
    "Directs work",
    "Drives engagement",
    "Financial acumen",
    "Global perspective",
    "Cultivates innovation",
    "Interpersonal savy",
    "Builds network",
    "Nimble learning",
    "Organizational savy",
    "Persuades",
]
export default skills
